version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build: ../api
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports: ["8080:8080"]
    restart: unless-stopped

  bot:
    build: ../bot
    env_file: ../.env
    depends_on:
      - api
      - redis
    ports: ["8081:8081"]
    volumes:
      - bot_store:/app/.wa_store   # Simpan sesi Baileys (QR pairing)
      - uploads:/app/uploads       # Media (gambar progress, invois PDF)
    restart: unless-stopped

  web:
    build: ../web
    env_file: ../.env
    depends_on: [api]
    ports: ["3000:3000"]
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
  bot_store:
  uploads:
